### ISSUE TITLE
Is onSuggestionFocused actually working?

### ISSUE THREAD

**Issue by diegohaz** [moroshko/react-autosuggest#168]
I need to know when and which suggestion is focused (not selected yet). I read in old issues that there was a `onSuggestionFocused` property, but It's not documented and I wasn't able to use it.

**Comment by moroshko** [comment]
`onSuggestionFocused` and `onSuggestionUnfocused` were removed in v3.0.
Can I ask what's your use case for `onSuggestionFocused`?

**Comment by diegohaz** [comment]
Hi, @moroshko. I'm using autosuggest to render a search song input. 
![image](https://cloud.githubusercontent.com/assets/3068563/15272011/0c5e1948-1a3c-11e6-97d9-f0fa14e6263e.png)
When a suggestion is focused, I need to toggle a property on it to display a play button (indicating that the song will play when suggestion is selected).

**Comment by moroshko** [comment]
Can't you use the `suggestionFocused` style to show/hide the play button? You already have a grey background style for the focused suggestion, so you should be able to do something like this:
```css
.playButton {
  display: none;
}
.react-autosuggest__suggestion--focused .playButton {
  display: inline;
}
```

**Comment by diegohaz** [comment]
The `.playButton` is actually something like `.SongListItem__SongControl`. It's in another component. I can do that, but I would not feel comfortable trespassing its scope. I would like to just toggle a property in my suggestion component. Do you have another solution?

**Comment by diegohaz** [comment]
To be more specific, the "display play button" do more than a `display: inline`. It's something like:
```css

.control {
  transform: scale(0);
  transition: transform 100ms ease-in-out;
}

.control.focused {
  transform: scale(1);
}
```
It's a specific rule for this component, and if it changes someday, would be nice to just change this component.
