### ISSUE TITLE
Adjust position of text input cursor 

### ISSUE THREAD

**Issue by Extra-lightwill** [moroshko/react-autosuggest#299]
Not sure how I would adjust the text input cursor position so there is a space between the left-edge of the search bar and the text cursor?

**Comment by moroshko** [comment]
Do you mean adding a left padding to the input:
```css
.react-autosuggest__input {
  padding-left: 20px;
}
```
or something else?
